# Generated by Django 4.2.20 on 2025-03-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('isAvailable', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=50)),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('enrollment_date', models.DateField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('total_units', models.FloatField()),
                ('create_at', models.DateField()),
                ('grade_level', models.FloatField()),
                ('email', models.EmailField(max_length=100)),
                ('gpa', models.FloatField()),
                ('major_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.major')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10)),
                ('term', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.student')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('create_at', models.DateField()),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.department')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.course')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.student')),
            ],
        ),
        migrations.CreateModel(
            name='Current_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField()),
                ('isDropped', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.course')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='major_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.major'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.classroom'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.semester'),
        ),
    ]
