# Generated by Django 4.2.20 on 2025-03-14 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment_history',
            unique_together={('student_id', 'course_id', 'semester')},
        ),
    ]
