# Generated by Django 4.2.20 on 2025-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorsCalendarevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'administrators_calendarevent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAdminprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_adminprofile',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='userprofessor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userstudent',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
