# Generated by Django 4.2.20 on 2025-04-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_administratorscalendarevent_useradminprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_adminprofile',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserAdminprofile',
        ),
    ]
