# Generated by Django 4.2.20 on 2025-04-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofessor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='grade_level',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='Freshman', max_length=10),
        ),
    ]
