# Generated by Django 4.2.20 on 2025-04-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_adminprofile_delete_useradminprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={},
        ),
    ]
