# Generated by Django 4.2.20 on 2025-04-06 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_alter_adminprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='adminprofile_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adminprofile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', upload_to='avatars/'),
        ),
        migrations.AlterModelTable(
            name='adminprofile',
            table=None,
        ),
    ]
